homeTimezone: America/New_York
api:
  host: http://localhost
  path: /otp/routers/default
  basePath: /otp
  port: 8080
  v2: true

map:
  initLat: 40.730610
  initLon: -73.935242
  baseLayers:
    - name: OSM Bright
      url: //tiles.stadiamaps.com/styles/osm_bright.json
      attribution: 'Map tiles: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    - name: Streets
      url: //basemaps.cartocdn.com/gl/positron-gl-style/style.json
      attribution: 'Map tiles: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
  transitive:
    labeledModes:
      - BUS
    styles:
      labels:
        font-size: 14px
        font-family: Hind, sans-serif
      segment_labels:
        border-color: "#FFFFFF"
        border-radius: 6
        border-width: 2
        color: "#FFE0D0"
        font-family: Hind, sans-serif
        font-size: 18px
    disableFlexArc: true

modes:
  modeButtons:
    - iconName: bus
      key: transit
      modes:
        - mode: TRANSIT
  initialState:
    enabledModeButtons: 
      - transit
  transitModes:
    - mode: BUS
      label: Bus
      color: blue

routingTypes:
  - key: ITINERARY
    text: Exact Time

itinerary:
  showRouteFares: false
  showPlanFirstLastButtons: false
  strictItineraryFiltering: true
  renderRouteNamesInBlocks: true
  fillModeIcons: true
  allowUserAlertCollapsing: true
  defaultFareType: { mediumId: null, riderCategoryId: null }

  showHeaderText: false
  showBatchUiItineraryHeaders: false
  hideSkeletons: true
  customBatchUiBackground: true
  groupByMode: true
  groupTransitModes: true
  mergeItineraries: true
  showFirstResultByDefault: false
  disableMetroSeperatorDot: false
  onlyShowCountdownForRealtime: true
  showScheduleDeviation: true
  showLegDurations: false
  previewOverlay: true
  displayA11yError: false
  defaultSort: "BEST"
  sortModes: 
    - 'BEST'
    - 'DURATION'
    - 'ARRIVALTIME'
    - 'DEPARTURETIME'
    - 'WALKTIME'

modeGroups:
  - name: Transit
    modes:
      - BUS

onTimeThresholdSeconds: 60

routeViewer:
  maxRealtimeVehicleAge: 60
  vehiclePositionRefreshSeconds: 10

nearbyView:
  radius: 1000